cc = g++
nvcc = nvcc
OBJ_DIR = ./obj
SRC_DIR = ./code
CFLAGS=-I./include  -L/usr/local/lib -lnuma -g  -mcmodel=large -O0 -std=c++17 -lpthread  -Wno-deprecated -mavx512bw -mavx512vl -mavx512f -mavx512cd -mavx512dq -msse -Wmultichar -mavx512vpopcntdq
CUDAFLAGS=-I./include -L/usr/local/lib  -O0 -g  -std=c++11 -lnuma
SRC_SEL = $(wildcard $(SRC_DIR)/select/*.cpp)
OBJ_SEL = $(patsubst $(SRC_DIR)/select/%.cpp, $(OBJ_DIR)/select/%.o, $(SRC_SEL))
SRC_PRO = $(wildcard $(SRC_DIR)/project/*.cpp)
OBJ_PRO = $(patsubst $(SRC_DIR)/project/%.cpp, $(OBJ_DIR)/project/%.o, $(SRC_PRO))
SRC_JOIN = $(wildcard $(SRC_DIR)/join/*.cpp)
OBJ_JOIN = $(patsubst $(SRC_DIR)/join/%.cpp, $(OBJ_DIR)/join/%.o, $(SRC_JOIN))
SRC_GROUP = $(wildcard $(SRC_DIR)/group/*.cpp)
OBJ_GROUP = $(patsubst $(SRC_DIR)/group/%.cpp, $(OBJ_DIR)/group/%.o, $(SRC_GROUP))
SRC_AGG = $(wildcard $(SRC_DIR)/aggregation/*.cpp)
OBJ_AGG = $(patsubst $(SRC_DIR)/aggregation/%.cpp, $(OBJ_DIR)/aggregation/%.o, $(SRC_AGG))
SRC_STARJOIN = $(wildcard $(SRC_DIR)/starjoin/*.cpp)
OBJ_STARJOIN = $(patsubst $(SRC_DIR)/starjoin/%.cpp, $(OBJ_DIR)/starjoin/%.o, $(SRC_STARJOIN))
SRC_OLAPCORE = $(wildcard $(SRC_DIR)/multi_compute_operator/*.cpp)
OBJ_OLAPCORE = $(patsubst $(SRC_DIR)/multi_compute_operator/%.cpp, $(OBJ_DIR)/multi_compute_operator/%.o, $(SRC_OLAPCORE))
SRC_GPUOLAPCORE = $(wildcard $(SRC_DIR)/gpu_multi_compute_operator/*.cu)
OBJ_GPUOLAPCORE = $(patsubst $(SRC_DIR)/gpu_multi_compute_operator/%.cu, $(OBJ_DIR)/gpu_multi_compute_operator/%.o, $(SRC_GPUOLAPCORE))
SRC_Q5 = $(wildcard $(SRC_DIR)/final_test/*.cpp)
OBJ_Q5 = $(patsubst $(SRC_DIR)/final_test/%.cpp, $(OBJ_DIR)/final_test/%.o, $(SRC_Q5))
ALL : project_test
#select_test project_test join_test group_test aggregation_test starjoin_test OLAPcore GPUOLAPcore

# select_test: $(OBJ_SEL)
# 	$(cc)  $<  $(CFLAGS)  -o   $@
# $(OBJ_SEL): $(SRC_SEL)
# 	$(cc) -c $(CFLAGS)  $< -o $@

project_test: $(OBJ_PRO)
	$(cc)  $<  $(CFLAGS)  -o   $@
$(OBJ_PRO): $(SRC_PRO)
	$(cc) -c $(CFLAGS)  $< -o $@

# join_test: $(OBJ_JOIN)
# 	$(cc)  $<  $(CFLAGS)  -o   $@
# $(OBJ_JOIN): $(SRC_JOIN)
# 	$(cc) -c $(CFLAGS)  $< -o $@
#group_test: $(OBJ_GROUP)
#	$(cc)  $<  $(CFLAGS)  -o   $@
#$(OBJ_GROUP): $(SRC_GROUP)
#	$(cc) -c $(CFLAGS)  $< -o $@
#aggregation_test: $(OBJ_AGG)
#	$(cc)  $<  $(CFLAGS)  -o   $@
#$(OBJ_AGG): $(SRC_AGG)
#	$(cc) -c $(CFLAGS)  $< -o $@
#
#starjoin_test: $(OBJ_STARJOIN)
#	$(cc)  $<  $(CFLAGS)  -o   $@
#$(OBJ_STARJOIN): $(SRC_STARJOIN)
#	$(cc) -c $(CFLAGS)  $< -o $@
#
#OLAPcore: $(OBJ_OLAPCORE)
#	$(cc)  $<  $(CFLAGS)  -o   $@
#$(OBJ_OLAPCORE): $(SRC_OLAPCORE)
#	$(cc) -c $(CFLAGS)  $< -o $@
#
#GPUOLAPcore: $(OBJ_GPUOLAPCORE)
#	$(nvcc)  $<  $(CUDAFLAGS)  -o   $@
#$(OBJ_GPUOLAPCORE): $(SRC_GPUOLAPCORE)
#	$(nvcc) -c $(CUDAFLAGS)  $< -o $@
#
#Q5: $(OBJ_Q5)
#	$(cc)  $<  $(CFLAGS)  -o   $@
#$(OBJ_Q5): $(SRC_Q5)
#	$(cc) -c $(CFLAGS)  $< -o $@
clean:
	rm -rf $(OBJ_SEL) $(OBJ_PRO) $(OBJ_JOIN) $(OBJ_GROUP)  $(OBJ_AGG)  $(OBJ_STARJOIN) $(OBJ_OLAPCORE) $(OBJ_Q5) select_test project_test join_test group_test starjoin_test OLAPcore GPUOLAPcore Q5

.PHONY: clean ALL
